version: '3'

services:
db:
image: postgres:14.3

restart: always
ports: - "5432:5432"

environment:
POSTGRES_PASSWORD: ${DB_PASSWORD}
POSTGRES_DB: ${gallery}
conteiner_name: contenedor1
volumes:
- ./postgres:/var/lib/postgresql/data